from PyQt5 import QtCore, QtGui, QtWidgets
#import USERS_GB_BG_rc
#import USERS_LOGO_rc
#import USERS_TB_BG_rc
from QRC_FILES import USERS_LOGO, USERS_TB_BG, USERS_GB_BG
from UPDATE_USERS import *
import sys
import os
import pickle
import mysql.connector

mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
if mydb.is_connected():
     print("Successfully Connected")
AMU_CURSOR = mydb.cursor()
AMU_CURSOR.execute("use sms")

def add_data(staffid, username, password, FirstName, LastName):
    query = "insert into users(Staff_ID, Username, Password, First_Name, Last_Name) values(%s, %s, %s, %s, %s)"
    global icon
    msg = QtWidgets.QMessageBox()
    try:
        AMU_CURSOR.execute(query, (staffid, username, password, FirstName, LastName))
        mydb.commit()
        msg.setWindowTitle("School Management System")
        msg.setText("New user added Successfully")
        msg.setWindowIcon(icon)
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.exec_()
    except Exception as e:
        msg.setWindowTitle("School Management System")
        msg.setText(f"{e}")
        msg.setWindowIcon(icon)
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.exec_()

class Ui_Users(object):
    global icon
    def setup_add_manage_users(self, Users):
        global icon
        Users.setObjectName("Users")
        Users.resize(1450, 714)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Users.sizePolicy().hasHeightForWidth())
        Users.setSizePolicy(sizePolicy)
        Users.setMinimumSize(QtCore.QSize(1450, 714))
        Users.setMaximumSize(QtCore.QSize(1450, 714))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        Users.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PIC/Pictures/Main_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Users.setWindowIcon(icon)
        Users.setStyleSheet("background-color: rgb(0, 0, 0);")
        Users.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Users)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(680, 70, 731, 541))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-image: url(:/PIC/Pictures/BG.jpg);")
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 40, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(1)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 70, 301, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setStyleSheet("background-image: url(:/PIC/Pictures/TB_PIC.png);")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhSensitiveData)
        self.lineEdit.setFrame(False)
        self.lineEdit.setPlaceholderText("Enter Staff ID")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(30, 110, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setLineWidth(1)
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 140, 301, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setStyleSheet("background-image: url(:/PIC/Pictures/TB_PIC.png);")
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setPlaceholderText("Enter Username")
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(380, 110, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(1)
        self.label_8.setObjectName("label_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 140, 311, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_3.setStyleSheet("background-image: url(:/PIC/Pictures/TB_PIC.png);")
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setPlaceholderText("Enter Password")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(30, 190, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(1)
        self.label_9.setObjectName("label_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 220, 661, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_4.setStyleSheet("background-image: url(:/PIC/Pictures/TB_PIC.png);")
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setPlaceholderText("Enter First Name")
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(30, 270, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setLineWidth(1)
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 300, 661, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_5.setStyleSheet("background-image: url(:/PIC/Pictures/TB_PIC.png);")
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setPlaceholderText("Enter Last Name")
        self.lineEdit_5.setClearButtonEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 350, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clear_bn)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 350, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.save_bn)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 440, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.load_db)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 440, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.delete_selected_user)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 400, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.update_record)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 631, 661))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        Users.setCentralWidget(self.centralwidget)
        self.tableWidget.cellClicked.connect(self.cell_clicked)

        self.retranslateUi(Users)
        QtCore.QMetaObject.connectSlotsByName(Users)

    def retranslateUi(self, Users):
        _translate = QtCore.QCoreApplication.translate
        Users.setWindowTitle(_translate("Users", "Add and Manage Users"))
        self.groupBox.setTitle(_translate("Users", "Add Users"))
        self.label_6.setText(_translate("Users", "Staff ID"))
        self.label_7.setText(_translate("Users", "Username"))
        self.label_8.setText(_translate("Users", "Password"))
        self.label_9.setText(_translate("Users", "First Name"))
        self.label_10.setText(_translate("Users", "Last Name"))
        self.pushButton.setText(_translate("Users", "Clear"))
        self.pushButton_2.setText(_translate("Users", "Save"))
        self.pushButton_3.setText(_translate("Users", "Refresh List"))
        self.pushButton_4.setText(_translate("Users", "Delete Selected User"))
        self.pushButton_5.setText(_translate("Users", "Update Record"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Users", "Staff ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Users", "Username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Users", "Password"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Users", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Users", "Last Name"))

    def clear_bn(self):
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")
        self.lineEdit_4.setText("")
        self.lineEdit_5.setText("")

    def save_bn(self):
        global icon
        mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
        if mydb.is_connected():
        	print("Successfully Connected")
        AMU_CURSOR = mydb.cursor()
        AMU_CURSOR.execute("use sms")
        flow = 0
        staffid = self.lineEdit.text()
        username = self.lineEdit_2.text()
        password = self.lineEdit_3.text()
        Firstname = self.lineEdit_4.text()
        Lastname = self.lineEdit_5.text()
        msg = QtWidgets.QMessageBox()       
        if staffid == "" or username == "" or password == "" or Firstname == "" or Lastname == "":
            msg.setWindowTitle("School Management System")
            msg.setText("Some or all the fields are Empty, please try again")
            msg.setWindowIcon(icon)
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.exec_()
        else:
            flow +=1

        if flow == 1:
            add_data(staffid, username, password, Firstname, Lastname)
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
        mydb.close()


    def load_db(self):
        mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
        if mydb.is_connected():
        	print("Successfully Connected")
        AMU_CURSOR = mydb.cursor()
        AMU_CURSOR.execute("use sms")
        self.tableWidget.setRowCount(0)
        AMU_CURSOR.execute("use sms")
        AMU_CURSOR.execute("select *from users")
        records = AMU_CURSOR.fetchall()
        print(records)
        for row_number, row_record in enumerate(records):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_record):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        mydb.close()

    def delete_selected_user(self):
        global icon
        mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
        if mydb.is_connected():
        	print("Successfully Connected")
        AMU_CURSOR = mydb.cursor()
        AMU_CURSOR.execute("use sms")
        selected_Id = self.tableWidget.currentItem().text()
        current_column = self.tableWidget.currentColumn()
        current_row = self.tableWidget.currentRow()
        msg = QtWidgets.QMessageBox()
        control = 0
        try:
            del_ID = int(selected_Id)
            control += 1
            if current_column != 0:
                pass
            else:
                control += 1
        except Exception as e:
            if selected_Id == None and current_column == None:
                msg.setText("Please select an ID to delete the user's record")
                msg.setWindowIcon(icon)
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setWindowTitle("School Management System")
                msg.exec_()
            else:
                msg.setText("Error! Please select an ID to delete the user's record")
                msg.setWindowIcon(icon)
                msg.setIcon(QtWidgets.QMessageBox.Warning)
                msg.setWindowTitle("School Management System")
                msg.exec_()

        print(control)
        if control == 2:
            if type(del_ID) == int and current_column == 0:
                AMU_CURSOR.execute("use sms")
                AMU_CURSOR.execute(f"delete from users where Staff_ID = {int(del_ID)}")
                mydb.commit()
                self.tableWidget.removeRow(current_row)
                msg.setText("User Record Successfully Deleted!")
                msg.setWindowTitle("School Management System")
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setWindowIcon(icon)
                msg.exec_()
        elif control == 1:
            msg.setText("Error! Please select an ID to delete the user's record")
            msg.setWindowIcon(icon)
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setWindowTitle("School Management System")
            msg.exec_()
        mydb.close()

    def update_record(self):
        global icon
        mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
        if mydb.is_connected():
            print("Successfully Connected")
        AMU_CURSOR = mydb.cursor()
        msg = QtWidgets.QMessageBox()
        try:
            current_row = self.tableWidget.currentRow()
            staff_id = self.tableWidget.item(current_row, 0).text()
            username = self.tableWidget.item(current_row, 1).text()
            password = self.tableWidget.item(current_row, 2).text()
            first_name = self.tableWidget.item(current_row, 3).text()
            last_name = self.tableWidget.item(current_row, 4).text()
            l = [staff_id, username, password, first_name, last_name]
            with open("user_update.dat", "wb") as f:
                pickle.dump(l, f)
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_Update_Users()
            self.ui.setup_update_users(self.window) 	
            self.window.show()
        except Exception as e:
            print(e)
            msg.setWindowTitle("School Management System")
            msg.setText("Please select a record first")
            msg.setWindowIcon(icon)
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.exec_()
        mydb.close()


    def cell_clicked(self):
        selected_Id = self.tableWidget.currentItem().text()
        current_column = self.tableWidget.currentColumn()
        try:
            del_ID = int(selected_Id)
        except Exception as e:
            pass


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Users = QtWidgets.QMainWindow()
    ui = Ui_Users()
    ui.setup_add_manage_users(Users)
    Users.show()
    sys.exit(app.exec_())
