from PyQt5 import QtCore, QtGui, QtWidgets
#import MANAGE_TEACHERS_B_rc
#import MANAGE_TEACHERS_LOGO_rc
#import MANAGE_TEACHERS_TB_rc
from QRC_FILES import MANAGE_TEACHERS_B, MANAGE_TEACHERS_LOGO, MANAGE_TEACHERS_TB
from ADD_NEW_TEACHER import *
from UPDATE_TEACHER import *
import sys
import os
import pickle
import mysql.connector

mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
if mydb.is_connected():
     print("Successfully Connected")
MNT_CURSOR = mydb.cursor()
mydb.close()

class Ui_Manage_Teachers(object):
    def setup_manage_teachers(self, Manage_Teachers):
        global icon
        Manage_Teachers.setObjectName("Manage_Teachers")
        Manage_Teachers.resize(1162, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Manage_Teachers.sizePolicy().hasHeightForWidth())
        Manage_Teachers.setSizePolicy(sizePolicy)
        Manage_Teachers.setMinimumSize(QtCore.QSize(1162, 750))
        Manage_Teachers.setMaximumSize(QtCore.QSize(1162, 750))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        Manage_Teachers.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/BG/Pictures/Main_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Manage_Teachers.setWindowIcon(icon)
        Manage_Teachers.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Manage_Teachers)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 1125, 541))
        self.tableWidget.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 1125, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setStyleSheet("background-image: url(:/BG/Pictures/TB_PIC.png);")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhSensitiveData)
        self.lineEdit.setFrame(False)
        self.lineEdit.setPlaceholderText("Search")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 650, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_2.setStyleSheet("background-image: url(:/BG/Pictures/BG.jpg);")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.load_db)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 650, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton.setStyleSheet("background-image: url(:/BG/Pictures/BG.jpg);")
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.ant_open)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(910, 650, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_4.setStyleSheet("background-image: url(:/BG/Pictures/BG.jpg);")
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.update_record)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 650, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_3.setStyleSheet("background-image: url(:/BG/Pictures/BG.jpg);")
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.delete_selected_teacher)
        self.tableWidget.cellClicked.connect(self.cell_clicked)
        Manage_Teachers.setCentralWidget(self.centralwidget)

        self.retranslateUi(Manage_Teachers)
        QtCore.QMetaObject.connectSlotsByName(Manage_Teachers)

    def retranslateUi(self, Manage_Teachers):
        _translate = QtCore.QCoreApplication.translate
        Manage_Teachers.setWindowTitle(_translate("Manage_Teachers", "Manage Teachers"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Manage_Teachers", "Staff ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Manage_Teachers", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Manage_Teachers", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Manage_Teachers", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Manage_Teachers", "Age"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Manage_Teachers", "Designation"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Manage_Teachers", "Address"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Manage_Teachers", "Contact"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Manage_Teachers", "Email ID"))
        self.pushButton_2.setText(_translate("Manage_Teachers", "Refresh List"))
        self.pushButton.setText(_translate("Manage_Teachers", "Add New Teacher(s)"))
        self.pushButton_4.setText(_translate("Manage_Teachers", "Update Record"))
        self.pushButton_3.setText(_translate("Manage_Teachers", "Delete Selected Teacher"))

    def load_db(self):
        mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
        if mydb.is_connected():
            print("Successfully Connected")
        MNT_CURSOR = mydb.cursor()
        msg = QtWidgets.QMessageBox()
        self.tableWidget.setRowCount(0)
        MNT_CURSOR.execute("use sms")
        MNT_CURSOR.execute("select *from Teachers")
        records = MNT_CURSOR.fetchall()
        print(records)
        for row_number, row_record in enumerate(records):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_record):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        mydb.close()

    def ant_open(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Add_New_Teachers()
        self.ui.setup_add_new_teachers(self.window)
        self.window.show()

    def delete_selected_teacher(self):
        global icon
        mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
        if mydb.is_connected():
            print("Successfully Connected")
        MNT_CURSOR = mydb.cursor()
        msg = QtWidgets.QMessageBox()
        selected_Id = self.tableWidget.currentItem().text()
        current_column = self.tableWidget.currentColumn()
        current_row = self.tableWidget.currentRow()
        msg = QtWidgets.QMessageBox()
        control = 0
        try:
            del_ID = int(selected_Id)
            control += 1
            if current_column != 0:
                pass
            else:
                control += 1
        except Exception as e:
            if selected_Id == None and current_column == None:
                msg.setText("Please select an ID to delete the teacher's record")
                msg.setWindowIcon(icon)
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setWindowTitle("School Management System")
                msg.exec_()
            else:
                msg.setText("Error! Please select an ID to delete the teacher's record")
                msg.setWindowIcon(icon)
                msg.setIcon(QtWidgets.QMessageBox.Warning)
                msg.setWindowTitle("School Management System")
                msg.exec_()

        print(control)
        if control == 2:
            if type(del_ID) == int and current_column == 0:
                print("Hello World")
                MNT_CURSOR.execute("use sms")
                MNT_CURSOR.execute(f"delete from teachers where Staff_ID = {int(del_ID)}")
                mydb.commit()
                self.tableWidget.removeRow(current_row)
                msg.setText("Student Record Successfully Deleted!")
                msg.setWindowTitle("School Management System")
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setWindowIcon(icon)
                msg.exec_()
        elif control == 1:
            msg.setText("Error! Please select an ID to delete the teacher's record")
            msg.setWindowIcon(icon)
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setWindowTitle("School Management System")
            msg.exec_()
        mydb.close()

    def update_record(self):
        global icon
        mydb = mysql.connector.connect(host = "localhost", user = "root", password = "ilkr1475")
        if mydb.is_connected():
            print("Successfully Connected")
        MNT_CURSOR = mydb.cursor()
        msg = QtWidgets.QMessageBox()
        try:
            current_row = self.tableWidget.currentRow()
            staff_id = self.tableWidget.item(current_row, 0).text()
            first_name = self.tableWidget.item(current_row, 1).text()
            last_name = self.tableWidget.item(current_row, 2).text()
            gender = self.tableWidget.item(current_row, 3).text()
            age = int(self.tableWidget.item(current_row, 4).text())
            designation = self.tableWidget.item(current_row, 5).text()
            address = self.tableWidget.item(current_row, 6).text()
            contact = self.tableWidget.item(current_row, 7).text()
            email_id = self.tableWidget.item(current_row, 8).text()
            l = [staff_id, first_name, last_name, gender, age, designation, address, contact, email_id]
            with open("teachers_update.dat", "wb") as f:
                pickle.dump(l, f)
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_Update_Teacher()
            self.ui.setup_update_teacher_ui(self.window)
            self.window.show()
        except Exception as e:
            print(e)
            msg.setWindowTitle("School Management System")
            msg.setText("Please select a record first")
            msg.setWindowIcon(icon)
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.exec_()
        mydb.close()         


    def cell_clicked(self):
        selected_Id = self.tableWidget.currentItem().text()
        current_column = self.tableWidget.currentColumn()
        try:
            del_ID = int(selected_Id)
        except Exception as e:
            pass

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Manage_Teachers = QtWidgets.QMainWindow()
    ui = Ui_Manage_Teachers()
    ui.setup_manage_teachers(Manage_Teachers)
    Manage_Teachers.show()
    sys.exit(app.exec_())
