from PyQt5 import QtCore, QtGui, QtWidgets
#import SMS_BG_rc
#import SMS_ICON_rc
#import SMS_Main_I_Logo_rc
from QRC_FILES import SMS_ICON, SMS_BG, SMS_Main_I_Logo
from ADD_NEW_STUDENT import *
from MANAGE_STUDENTS import *
from ADD_NEW_TEACHER import *
from MANAGE_TEACHERS import *
from ADD_NEW_STAFF import *
from MANAGE_STAFF import *
from ADD_MANAGE_USERS import *
from CREATE_SUBJECTS_NEW_TEMP import *

class Ui_MAIN_INTERFACE(object):
    global icon
    def setup_sms_main_interface(self, MAIN_INTERFACE):
        global icon
        MAIN_INTERFACE.setObjectName("MAIN_INTERFACE")
        MAIN_INTERFACE.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MAIN_INTERFACE.sizePolicy().hasHeightForWidth())
        MAIN_INTERFACE.setSizePolicy(sizePolicy)
        MAIN_INTERFACE.setMinimumSize(QtCore.QSize(0, 0))
        MAIN_INTERFACE.setMaximumSize(QtCore.QSize(1920, 1080))
        MAIN_INTERFACE.showMaximized()
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        MAIN_INTERFACE.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LOGO/Pictures/Main_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MAIN_INTERFACE.setWindowIcon(icon)
        MAIN_INTERFACE.setStyleSheet("background-color: rgb(0, 0, 0);\n""\n""")
        MAIN_INTERFACE.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MAIN_INTERFACE)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(1260, 580, 631, 451))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.calendarWidget.setPalette(palette)
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.LongDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1270, 50, 611, 491))
        self.label.setStyleSheet("background-image: url(:/PIC/Pictures/Logo.jpg);\n"
"border-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/PIC/Pictures/Logo.jpg"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 100, 821, 891))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(150, 70, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ICONS/Pictures/add student.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(5, 5))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.ans_open)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 70, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.mns_open)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 91))
        self.label_2.setStyleSheet("background-image: url(:/ICONS/Pictures/ADD_STUDENT_P.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/ADD_STUDENT_P.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(410, 70, 111, 91))
        self.label_3.setStyleSheet("background-image: url(:/ICONS/Pictures/students.png.webp);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/students.png.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 210, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.ant_open)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(50, 210, 81, 81))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/add teacher.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 210, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.mnt_open)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(420, 210, 81, 81))
        self.label_7.setStyleSheet("")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/add teacher.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 350, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.ansf_open)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(50, 340, 81, 91))
        self.label_8.setStyleSheet("background-image: url(:/ICONS/Pictures/staff.png);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/staff.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(540, 350, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.mnsf_open)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(440, 340, 81, 91))
        self.label_9.setStyleSheet("background-image: url(:/ICONS/Pictures/manage staff.png);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/manage staff.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(540, 490, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.amu_open)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(50, 480, 81, 91))
        self.label_10.setStyleSheet("background-image: url(:/ICONS/Pictures/users.webp);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/users.webp"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(150, 490, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.amu_open)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(440, 480, 81, 91))
        self.label_11.setStyleSheet("background-image: url(:/ICONS/Pictures/users.webp);")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/users.webp"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(540, 630, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.cs_open)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(50, 620, 81, 91))
        self.label_12.setStyleSheet("")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/subjects.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(440, 620, 81, 91))
        self.label_13.setStyleSheet("background-image: url(:/ICONS/Pictures/users.webp);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/subjects.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(150, 630, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.cs_open)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(150, 760, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setIconSize(QtCore.QSize(5, 5))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.about)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(50, 750, 81, 91))
        self.label_14.setStyleSheet("")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/ICONS/Pictures/SMS_ABOUT_P.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        MAIN_INTERFACE.setCentralWidget(self.centralwidget)

        self.retranslateUi(MAIN_INTERFACE)
        QtCore.QMetaObject.connectSlotsByName(MAIN_INTERFACE)



    def retranslateUi(self, MAIN_INTERFACE):
        _translate = QtCore.QCoreApplication.translate
        MAIN_INTERFACE.setWindowTitle(_translate("MAIN_INTERFACE", "School Management System - Main Interface"))
        self.groupBox.setTitle(_translate("MAIN_INTERFACE", "Actions"))
        self.pushButton.setText(_translate("MAIN_INTERFACE", "Add Student"))
        self.pushButton_2.setText(_translate("MAIN_INTERFACE", "Manage Students"))
        self.pushButton_5.setText(_translate("MAIN_INTERFACE", "Add Teacher"))
        self.pushButton_6.setText(_translate("MAIN_INTERFACE", "Manage Teachers"))
        self.pushButton_7.setText(_translate("MAIN_INTERFACE", "Add Staff"))
        self.pushButton_8.setText(_translate("MAIN_INTERFACE", "Manage  Staff"))
        self.pushButton_9.setText(_translate("MAIN_INTERFACE", "Manage Users"))
        self.pushButton_10.setText(_translate("MAIN_INTERFACE", "Add User"))
        self.pushButton_11.setText(_translate("MAIN_INTERFACE", "Manage Subjects"))
        self.pushButton_12.setText(_translate("MAIN_INTERFACE", "Create Subjects"))
        self.pushButton_13.setText(_translate("MAIN_INTERFACE", "About"))


    def ans_open(self):
    	self.window = QtWidgets.QMainWindow()
    	self.ui = Ui_Add_New_Student()
    	self.ui.setup_add_new_student_ui(self.window)
    	self.window.show()

    def mns_open(self):
    	self.window = QtWidgets.QMainWindow()
    	self.ui = Ui_Manage_Students()
    	self.ui.setup_manage_students(self.window)
    	self.window.show()

    def ant_open(self):
    	self.window = QtWidgets.QMainWindow()
    	self.ui = Ui_Add_New_Teachers()
    	self.ui.setup_add_new_teachers(self.window)
    	self.window.show()

    def mnt_open(self):
    	self.window = QtWidgets.QMainWindow()
    	self.ui = Ui_Manage_Teachers()
    	self.ui.setup_manage_teachers(self.window)
    	self.window.show()

    def ansf_open(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Add_Staff()
        self.ui.setup_add_new_staff(self.window)
        self.window.show()

    def mnsf_open(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Manage_Staff()
        self.ui.setup_manage_staff(self.window)
        self.window.show()

    def amu_open(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Users()
        self.ui.setup_add_manage_users(self.window)
        self.window.show()

    def cs_open(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Create_Subjects()
        self.ui.setup_create_subjects(self.window)
        self.window.show()

    def about(self):
        self.window = QtWidgets.QMessageBox()
        self.window .setWindowTitle("School Management System")
        self.window .setWindowIcon(icon)
        self.window .setText("The School Management System is developed by\nPrathamesh Bheeemanathi.")
        self.window .exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MAIN_INTERFACE = QtWidgets.QMainWindow()
    ui = Ui_MAIN_INTERFACE()
    ui.setup_sms_main_interface(MAIN_INTERFACE)
    MAIN_INTERFACE.show()
    sys.exit(app.exec_())
